"""generated by CDK init for based setup"""
import setuptools


with open("README.md") as fp:
    long_description = fp.read()


setuptools.setup(
    name="swift_main_stack",
    version="0.0.1",

    description="Quick Start for SWIFT Connectivity",
    long_description=long_description,
    long_description_content_type="text/markdown",

    author="Jack Iu - AWS",

    package_dir={"": "swift_main_stack"},
    packages=setuptools.find_packages(where="swift_main_stack"),

    install_requires=[
        # removing hard-coded versions
        "aws-cdk-lib",
        "constructs",
        "cdk_ec2_key_pair",
        "boto3",
    ],

    python_requires=">=3.6",

    classifiers=[
        "Development Status :: 4 - Beta",

        "Intended Audience :: Developers",

        "License :: OSI Approved :: Apache Software License",

        "Programming Language :: JavaScript",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",

        "Topic :: Software Development :: Code Generators",
        "Topic :: Utilities",

        "Typing :: Typed",
    ],
)
